- name: Create a Paloalto Firewall Tunnel
  hosts: ALL
  connection: local
  gather_facts: False
     


  vars:
    server: 192.168.35.135
    

  #collections:
  #   - paloaltonetworks.panos

  #roles:
   #  - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  #- name: Load Variables
  #  include_vars: vars1.yml
  
  #- name: new var
  #  include_vars: vars4.yml

  - name: Configure Tunnel Interface
    paloaltonetworks.panos.panos_tunnel:
      provider: 
        ip_address: "{{ server }}"
        api_key: LUFRPT1NaXdwcGRHQk9kWVVTUmpCY1IrRll2SUNpbVk9SkFla3ZuZ3RKNHdnOFl6bkx5TzFJendmdkdwY3V1c3Bmem43bS8rNE1NaUFiQUswd2xSZHVBTkdSVEN2bGpIcw==
      state: 'present'
      if_name: 'tunnel.3100'
      ip: '10.1.1.1/32'
      comment: 'Tunnel Interface for XYZ purpose'
      zone_name: 'inside'
      commit: False
    
        
